### ISSUE TITLE
Build error "Could not find artifact core:aqCore:jar:1.0 in repo.jenkins-ci.org"

### ISSUE THREAD

**Issue by lemeurherve** [jenkinsci/accelq-ci-connect-plugin#10]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  ci.jenkins.io

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

ci.jenkins.io

### Reproduction steps

Try to build the plugin, either on ci.jenkins.io or either locally with `mvn clean verify`

### Expected Results

A successful build.

### Actual Results

> [ERROR] Failed to execute goal on project accelq-ci-connect: Could not resolve dependencies for project com.aq:accelq-ci-connect:hpi:1.7-SNAPSHOT: Could not find artifact core:aqCore:jar:1.0 in repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/) -> [Help 1]

**Comment by lemeurherve** [comment]
Is this dependency private?

**Comment by NotMyFault** [comment]
A [Jenkinsfile](https://www.jenkins.io/doc/developer/tutorial-improve/add-a-jenkinsfile/) should be added to the repository to spot build failures easier.

**Comment by accelq** [comment]
Added closing this
