### ISSUE TITLE
Repo contents aren't right

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/accelq-ci-connect-plugin#3]
* `JenkinsFile` should be called `Jenkinsfile`.
* Delete (and add to `.gitignore`) `release.properties`, that is a temporary file that should never be committed.

The latter is also a likely explanation why you may have trouble releasing the plugin, assuming that's the reason for the nondefault publishing flow for version 1.1.

**Comment by accelq** [comment]
Ok, will take in the next release

**Comment by accelq** [comment]
Done
